import type { StencilMap } from "./types.js";

/**
 * Azure service → Visio stencil mapping.
 * 206 Azure services mapped to their official Visio stencil file and master shape name.
 */
export const STENCIL_MAP: StencilMap = {
  "azure/front-door": { stencil: "Azure-Web", master: "Front Door And Cdn Profiles" },
  "azure/cdn": { stencil: "Azure-Web", master: "Front Door And Cdn Profiles" },
  "azure/app-services": { stencil: "Azure-App Services", master: "App Services" },
  "azure/app-service-plans": { stencil: "Azure-App Services", master: "App Service Plans" },
  "azure/app-service-domains": { stencil: "Azure-App Services", master: "App Service Domains" },
  "azure/app-service-certificates": { stencil: "Azure-App Services", master: "App Service Certificates" },
  "azure/app-service-environments": { stencil: "Azure-App Services", master: "App Service Environments" },
  "azure/static-apps": { stencil: "Azure-Web", master: "Static Apps" },
  "azure/api-management": { stencil: "Azure-Web", master: "API Management Services" },
  "azure/api-connections": { stencil: "Azure-Web", master: "API Connections" },
  "azure/api-center": { stencil: "Azure-Web", master: "API Center" },
  "azure/cognitive-search": { stencil: "Azure-Web", master: "Cognitive Search" },
  "azure/signalr": { stencil: "Azure-Web", master: "Signalr" },
  "azure/notification-hubs": { stencil: "Azure-App Services", master: "Notification Hubs" },
  "azure/notification-hub-namespaces": { stencil: "Azure-Web", master: "Notification Hub Namespaces" },
  "azure/cognitive-services": { stencil: "Azure-Web", master: "Cognitive Services" },
  "azure/media-services": { stencil: "Azure-Web", master: "Azure Media Service" },
  "azure/spring-apps": { stencil: "Azure-Web", master: "Azure Spring Apps" },
  "azure/cosmos-db": { stencil: "Azure-Databases", master: "Azure Cosmos Db" },
  "azure/sql-database": { stencil: "Azure-Databases", master: "SQL Database" },
  "azure/sql-server": { stencil: "Azure-Databases", master: "SQL Server" },
  "azure/sql-managed-instance": { stencil: "Azure-Databases", master: "SQL Managed Instance" },
  "azure/sql-vm": { stencil: "Azure-Databases", master: "Azure SQL VM" },
  "azure/sql-elastic-pools": { stencil: "Azure-Databases", master: "SQL Elastic Pools" },
  "azure/mysql": { stencil: "Azure-Databases", master: "Azure Database Mysql Server" },
  "azure/postgresql": { stencil: "Azure-Databases", master: "Azure Database Postgresql Server" },
  "azure/mariadb": { stencil: "Azure-Databases", master: "Azure Database Mariadb Server" },
  "azure/sql-data-warehouse": { stencil: "Azure-Databases", master: "SQL Data Warehouses" },
  "azure/synapse-analytics": { stencil: "Azure-Databases", master: "Azure Synapse Analytics" },
  "azure/redis-cache": { stencil: "Azure-Databases", master: "Cache Redis" },
  "azure/data-explorer": { stencil: "Azure-Databases", master: "Azure Data Explorer Clusters" },
  "azure/oracle-database": { stencil: "Azure-Databases", master: "Oracle Database" },
  "azure/data-factory": { stencil: "Azure-Databases", master: "Data Factories" },
  "azure/database-migration-services": { stencil: "Azure-Databases", master: "Azure Database Migration Services" },
  "azure/storage-accounts": { stencil: "Azure-Storage", master: "Storage Accounts" },
  "azure/data-lake-storage": { stencil: "Azure-Storage", master: "Data Lake Storage Gen1" },
  "azure/data-box": { stencil: "Azure-Storage", master: "Data Box" },
  "azure/databox-gateway": { stencil: "Azure-Storage", master: "Azure Databox Gateway" },
  "azure/recovery-services-vaults": { stencil: "Azure-Storage", master: "Recovery Services Vaults" },
  "azure/storage-sync-services": { stencil: "Azure-Storage", master: "Storage Sync Services" },
  "azure/storsimple": { stencil: "Azure-Storage", master: "Storsimple Device Managers" },
  "azure/data-shares": { stencil: "Azure-Storage", master: "Data Shares" },
  "azure/netapp-files": { stencil: "Azure-Storage", master: "Azure Netapp Files" },
  "azure/virtual-networks": { stencil: "Azure-Networking", master: "Virtual Networks" },
  "azure/subnets": { stencil: "Azure-Networking", master: "Subnet" },
  "azure/network-security-groups": { stencil: "Azure-Networking", master: "Network Security Groups" },
  "azure/application-security-groups": { stencil: "Azure-Security", master: "Application Security Groups" },
  "azure/load-balancers": { stencil: "Azure-Networking", master: "Load Balancers" },
  "azure/application-gateway": { stencil: "Azure-Networking", master: "Application Gateways" },
  "azure/traffic-manager": { stencil: "Azure-Networking", master: "Traffic Manager Profiles" },
  "azure/public-ip-addresses": { stencil: "Azure-Networking", master: "Public Ip Addresses" },
  "azure/vpn-gateway": { stencil: "Azure-Networking", master: "Virtual Network Gateways" },
  "azure/expressroute": { stencil: "Azure-Networking", master: "Expressroute Circuits" },
  "azure/virtual-wan": { stencil: "Azure-Networking", master: "Virtual Wans" },
  "azure/virtual-wan-hub": { stencil: "Azure-Networking", master: "Virtual Wan Hub" },
  "azure/firewall": { stencil: "Azure-Networking", master: "Firewalls" },
  "azure/firewall-manager": { stencil: "Azure-Networking", master: "Azure Firewall Manager" },
  "azure/firewall-policy": { stencil: "Azure-Networking", master: "Azure Firewall Policy" },
  "azure/waf": { stencil: "Azure-Networking", master: "Web Application Firewall Policies(waf)" },
  "azure/ddos-protection": { stencil: "Azure-Networking", master: "Ddos Protection Plans" },
  "azure/dns-zones": { stencil: "Azure-Networking", master: "DNS Zones" },
  "azure/dns-private-resolver": { stencil: "Azure-Networking", master: "DNS Private Resolver" },
  "azure/private-endpoint": { stencil: "Azure-Other", master: "Private Endpoints" },
  "azure/private-link": { stencil: "Azure-Networking", master: "Private Link" },
  "azure/private-link-services": { stencil: "Azure-Networking", master: "Private Link Services" },
  "azure/service-endpoint-policies": { stencil: "Azure-Networking", master: "Service Endpoint Policies" },
  "azure/nat-gateway": { stencil: "Azure-Networking", master: "Nat" },
  "azure/bastion": { stencil: "Azure-Networking", master: "Bastions" },
  "azure/network-interfaces": { stencil: "Azure-Networking", master: "Network Interfaces" },
  "azure/route-tables": { stencil: "Azure-Networking", master: "Route Tables" },
  "azure/route-filters": { stencil: "Azure-Networking", master: "Route Filters" },
  "azure/network-watcher": { stencil: "Azure-Monitor", master: "Network Watcher" },
  "azure/on-premises-data-gateway": { stencil: "Azure-Networking", master: "On Premises Data Gateways" },
  "azure/local-network-gateway": { stencil: "Azure-Networking", master: "Local Network Gateways" },
  "azure/connections": { stencil: "Azure-Networking", master: "Connections" },
  "azure/virtual-machines": { stencil: "Azure-Compute", master: "Virtual Machine" },
  "azure/vm-scale-sets": { stencil: "Azure-Compute", master: "VM Scale Sets" },
  "azure/availability-sets": { stencil: "Azure-Compute", master: "Availability Sets" },
  "azure/disk-encryption-sets": { stencil: "Azure-Compute", master: "Disk Encryption Sets" },
  "azure/managed-disks": { stencil: "Azure-Compute", master: "Disks" },
  "azure/disk-snapshots": { stencil: "Azure-Compute", master: "Disks Snapshots" },
  "azure/images": { stencil: "Azure-Compute", master: "Images" },
  "azure/vm-images": { stencil: "Azure-Compute", master: "Image Definitions" },
  "azure/shared-image-galleries": { stencil: "Azure-Compute", master: "Shared Image Galleries" },
  "azure/image-templates": { stencil: "Azure-Compute", master: "Image Templates" },
  "azure/function-apps": { stencil: "Azure-Compute", master: "Function Apps" },
  "azure/container-instances": { stencil: "Azure-Containers", master: "Container Instances" },
  "azure/container-registries": { stencil: "Azure-Containers", master: "Container Registries" },
  "azure/kubernetes-services": { stencil: "Azure-Containers", master: "Kubernetes Services" },
  "azure/service-fabric": { stencil: "Azure-Containers", master: "Service Fabric Clusters" },
  "azure/batch": { stencil: "Azure-Containers", master: "Batch Accounts" },
  "azure/container-apps": { stencil: "Azure-Other", master: "Container Apps Environments" },
  "azure/key-vault": { stencil: "Azure-Security", master: "Key Vaults" },
  "azure/security-center": { stencil: "Azure-Security", master: "Microsoft Defender For Cloud" },
  "azure/sentinel": { stencil: "Azure-Security", master: "Azure Sentinel" },
  "azure/information-protection": { stencil: "Azure-Security", master: "Azure Information Protection" },
  "azure/defender-iot": { stencil: "Azure-Security", master: "Microsoft Defender For IOT" },
  "azure/defender-easm": { stencil: "Azure-Security", master: "Microsoft Defender Easm" },
  "azure/multifactor-authentication": { stencil: "Azure-Security", master: "Multifactor Authentication" },
  "azure/conditional-access": { stencil: "Azure-Security", master: "Conditional Access" },
  "azure/identity-protection": { stencil: "Azure-Identity", master: "Entra Id Protection" },
  "azure/privileged-identity-management": { stencil: "Azure-Identity", master: "Entra Privleged Identity Management" },
  "azure/managed-identities": { stencil: "Azure-Identity", master: "Managed Identities" },
  "azure/azure-ad": { stencil: "Azure-Identity", master: "Groups" },
  "azure/azure-ad-b2c": { stencil: "Azure-Identity", master: "Azure Ad B2c" },
  "azure/entra-connect": { stencil: "Azure-Identity", master: "Entra Connect" },
  "azure/entra-domain-services": { stencil: "Azure-Identity", master: "Entra Domain Services" },
  "azure/external-identities": { stencil: "Azure-Identity", master: "External Identities" },
  "azure/entra-global-secure-access": { stencil: "Azure-Identity", master: "Entra Global Secure Access" },
  "azure/users": { stencil: "Azure-Identity", master: "Users" },
  "azure/groups": { stencil: "Azure-Identity", master: "Groups" },
  "azure/enterprise-applications": { stencil: "Azure-Identity", master: "Enterprise Applications" },
  "azure/app-registrations": { stencil: "Azure-Identity", master: "App Registrations" },
  "azure/app-configuration": { stencil: "Azure-Integration", master: "App Configuration" },
  "azure/logic-apps": { stencil: "Azure-Integration", master: "Logic Apps" },
  "azure/logic-apps-custom-connector": { stencil: "Azure-Integration", master: "Logic Apps Custom Connector" },
  "azure/api-management-services": { stencil: "Azure-Integration", master: "API Management Services" },
  "azure/service-bus": { stencil: "Azure-Integration", master: "Azure Service Bus" },
  "azure/event-hubs": { stencil: "Azure-Analytics", master: "Event Hubs" },
  "azure/event-grid": { stencil: "Azure-Integration", master: "Event Grid Topics" },
  "azure/event-grid-domains": { stencil: "Azure-Integration", master: "Event Grid Domains" },
  "azure/event-grid-subscriptions": { stencil: "Azure-Integration", master: "Event Grid Subscriptions" },
  "azure/integration-accounts": { stencil: "Azure-Integration", master: "Integration Accounts" },
  "azure/integration-service-environments": { stencil: "Azure-Integration", master: "Integration Service Environments" },
  "azure/data-catalog": { stencil: "Azure-Integration", master: "Azure Data Catalog" },
  "azure/stream-analytics": { stencil: "Azure-Analytics", master: "Stream Analytics Jobs" },
  "azure/log-analytics": { stencil: "Azure-Analytics", master: "Log Analytics Workspaces" },
  "azure/application-insights": { stencil: "Azure-Monitor", master: "Application Insights" },
  "azure/monitor": { stencil: "Azure-Monitor", master: "Monitor" },
  "azure/activity-log": { stencil: "Azure-Monitor", master: "Activity Log" },
  "azure/diagnostics-settings": { stencil: "Azure-Monitor", master: "Diagnostics Settings" },
  "azure/metrics": { stencil: "Azure-Monitor", master: "Metrics" },
  "azure/alerts": { stencil: "Azure-Management + Governance", master: "Alerts" },
  "azure/auto-scale": { stencil: "Azure-Monitor", master: "Auto Scale" },
  "azure/azure-workbooks": { stencil: "Azure-Analytics", master: "Azure Workbooks" },
  "azure/change-analysis": { stencil: "Azure-Devops", master: "Change Analysis" },
  "azure/databricks": { stencil: "Azure-Analytics", master: "Azure Databricks" },
  "azure/hd-insight": { stencil: "Azure-Analytics", master: "Hd Insight Clusters" },
  "azure/data-lake-analytics": { stencil: "Azure-Analytics", master: "Data Lake Analytics" },
  "azure/power-bi-embedded": { stencil: "Azure-Analytics", master: "Power Bi Embedded" },
  "azure/analysis-services": { stencil: "Azure-Analytics", master: "Analysis Services" },
  "azure/devops-starter": { stencil: "Azure-Devops", master: "Devops Starter" },
  "azure/devops": { stencil: "Azure-Devops", master: "Azure Devops" },
  "azure/devtest-labs": { stencil: "Azure-Devops", master: "Devtest Labs" },
  "azure/load-testing": { stencil: "Azure-Devops", master: "Load Testing" },
  "azure/cloudtest": { stencil: "Azure-Devops", master: "Cloudtest" },
  "azure/automation-accounts": { stencil: "Azure-Management + Governance", master: "Automation Accounts" },
  "azure/blueprints": { stencil: "Azure-Management + Governance", master: "Blueprints" },
  "azure/policy": { stencil: "Azure-Management + Governance", master: "Policy" },
  "azure/cost-management": { stencil: "Azure-Management + Governance", master: "Cost Management And Billing" },
  "azure/advisor": { stencil: "Azure-Management + Governance", master: "Advisor" },
  "azure/resource-graph-explorer": { stencil: "Azure-Management + Governance", master: "Resource Graph Explorer" },
  "azure/lighthouse": { stencil: "Azure-Management + Governance", master: "Azure Lighthouse" },
  "azure/azure-arc": { stencil: "Azure-Management + Governance", master: "Azure Arc" },
  "azure/arc-machines": { stencil: "Azure-Management + Governance", master: "Arc Machines" },
  "azure/arc-kubernetes": { stencil: "Azure-Other", master: "Arc Kubernetes" },
  "azure/arc-postgresql": { stencil: "Azure-Other", master: "Arc Postgresql" },
  "azure/arc-sql-server": { stencil: "Azure-Other", master: "Arc SQL Server" },
  "azure/arc-sql-managed-instance": { stencil: "Azure-Other", master: "Arc SQL Managed Instance" },
  "azure/digital-twins": { stencil: "Azure-Iot", master: "Digital Twins" },
  "azure/iot-hub": { stencil: "Azure-Iot", master: "IOT Hub" },
  "azure/iot-central": { stencil: "Azure-Iot", master: "IOT Central Applications" },
  "azure/iot-edge": { stencil: "Azure-Iot", master: "IOT Edge" },
  "azure/iot-operations": { stencil: "Azure-Iot", master: "Azure IOT Operations" },
  "azure/device-provisioning-services": { stencil: "Azure-Iot", master: "Device Provisioning Services" },
  "azure/time-series-insights": { stencil: "Azure-Iot", master: "Time Series Insights Environments" },
  "azure/industrial-iot": { stencil: "Azure-Iot", master: "Industrial IOT" },
  "azure/azure-maps": { stencil: "Azure-Iot", master: "Azure Maps Accounts" },
  "azure/bot-services": { stencil: "Azure-Ai + Machine Learning", master: "Bot Services" },
  "azure/machine-learning": { stencil: "Azure-Ai + Machine Learning", master: "Machine Learning" },
  "azure/openai": { stencil: "Azure-Ai + Machine Learning", master: "Azure Openai" },
  "azure/ai-studio": { stencil: "Azure-Ai + Machine Learning", master: "AI Studio" },
  "azure/cognitive-services-decisions": { stencil: "Azure-Ai + Machine Learning", master: "Cognitive Services Decisions" },
  "azure/language": { stencil: "Azure-Ai + Machine Learning", master: "Language" },
  "azure/translator": { stencil: "Azure-Ai + Machine Learning", master: "Translator Text" },
  "azure/speech-services": { stencil: "Azure-Ai + Machine Learning", master: "Speech Services" },
  "azure/computer-vision": { stencil: "Azure-Ai + Machine Learning", master: "Computer Vision" },
  "azure/custom-vision": { stencil: "Azure-Ai + Machine Learning", master: "Custom Vision" },
  "azure/face-api": { stencil: "Azure-Ai + Machine Learning", master: "Face Apis" },
  "azure/content-moderator": { stencil: "Azure-Ai + Machine Learning", master: "Content Moderators" },
  "azure/personalizer": { stencil: "Azure-Ai + Machine Learning", master: "Personalizers" },
  "azure/qna-maker": { stencil: "Azure-Ai + Machine Learning", master: "Qna Makers" },
  "azure/anomaly-detector": { stencil: "Azure-Ai + Machine Learning", master: "Anomaly Detector" },
  "azure/form-recognizer": { stencil: "Azure-Ai + Machine Learning", master: "Form Recognizers" },
  "azure/metrics-advisor": { stencil: "Azure-Compute", master: "Metrics Advisor" },
  "azure/content-safety": { stencil: "Azure-Ai + Machine Learning", master: "Content Safety" },
  "azure/applied-ai-services": { stencil: "Azure-Ai + Machine Learning", master: "Azure Applied AI Services" },
  "azure/immersive-reader": { stencil: "Azure-Ai + Machine Learning", master: "Immersive Readers" },
  "azure/serverless-search": { stencil: "Azure-Ai + Machine Learning", master: "Serverless Search" },
  "azure/genomics": { stencil: "Azure-Ai + Machine Learning", master: "Genomics" },
  "azure/bonsai": { stencil: "Azure-Ai + Machine Learning", master: "Bonsai" },
  "azure/virtual-desktop": { stencil: "Azure-Other", master: "Azure Virtual Desktop" },
  "azure/vmware-solution": { stencil: "Azure-Other", master: "Azure Vmware Solution" },
  "azure/azure-sphere": { stencil: "Azure-Other", master: "Azure Sphere" },
  "azure/video-indexer": { stencil: "Azure-Other", master: "Azure Video Indexer" },
  "azure/video-analyzer": { stencil: "Azure-Other", master: "Video Analyzers" },
  "azure/communication-services": { stencil: "Azure-Other", master: "Azure Communication Services" },
  "azure/mysql-flexible-server": { stencil: "Azure-Databases", master: "Azure Database Mysql Server" },
  "azure/postgresql-flexible-server": { stencil: "Azure-Databases", master: "Azure Database Postgresql Server" },
  "azure/managed-grafana": { stencil: "Azure-Other", master: "Azure Managed Grafana" },
  "azure/managed-redis": { stencil: "Azure-New Icons", master: "Azure Managed Redis" },
  "azure/stack-hci": { stencil: "Azure-Iot", master: "Stack Hci Premium" },
  "azure/resource-groups": { stencil: "Azure-General", master: "Resource Groups" },
  "azure/subscriptions": { stencil: "Azure-General", master: "Subscriptions" },
  "azure/management-groups": { stencil: "Azure-General", master: "Management Groups" },
  "azure/user-settings": { stencil: "Azure-Security", master: "User Settings" },
  "c4/container": { stencil: "Azure-General", master: "Container" },
  "c4/actor": { stencil: "Azure-General", master: "User" },
  "c4/system": { stencil: "Azure-General", master: "System" },
};
